# -*- coding: utf-8 -*-
"""DAY1(content&programs).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iN2H5HuUpmRsq-GS2M-dMT0BBDJmecnU

INTRO

Python is famous in the market and it is called as the language of future
It supports current technologies and upcoming technologies.
Mediums: Idle-Interpreted development learning environment, Jupyter notebook, Anaconda, Thoni, VS code. python-scripting language

# Displaying name in mother tongue using unicode for letters
"""



"""# *Assignment-sudarsan,mounya """

print(chr(3128)+chr(3137)+chr(3110)+chr(3120)+chr(3149)+chr(3126)+chr(3112)+chr(3149))

print(chr(3118)+chr(3148)+chr(3112)+chr(3149)+chr(3119))

"""# Checking valid and invalid varaiable names"""

num1=11
_num2=80
num_3=49

4num=5
>num5=99
6=10

"""# Data types

*   Numerical data type - int,float,complex
*   Boolean Datatype - True,False
*   Sequence Datatype - string,list,tuple,dictionary

"""

#Numeric datatypes
print(type(11))
print(type(1.89))
print(type(1+2j))

#Boolean Datatype
print(type(True))
print(type(False))

#Sequence datatypes
print(type("satya"))
print(type([3,6,9]))

"""# Type Conversion"""

print(int(34.6))
print(id(56))
print(isinstance(10,int))
print(isinstance(10,float))

"""# *concatenating strings using type coversion"""

a=30
print("The value is:"+a)

a=54
print("the value is :"+str(a))

"""# Operators's Precedence and Associativity


Every operator has it's own priority.
we can use BODMAS rule
If there is same priority operators present in the expression,evaluation happens left to right except assignment operator(evaluates right to left)

# Input statement
*   input() --- by default --- string
-for int -- int(input())
-for float -- float(input())
-for complex -- complex(input())

PROGRAM--*Take 3 integers,3float numbers,2 strings and 1 complex number as input and print the same on the screen(note* use formatted output)
"""

int1=int(input("Enter first integer:"))
int2=int(input("Enter second integer:"))
int3=int(input("Enter third integer:"))
fl1=float(input("Enter first float:"))
fl2=float(input("Enter second float:"))
fl3=float(input("Enter third float:"))
string1=input("Enter first string:")
string2=input("Enter second string:")
cmpl=complex(input("Enter first complex:"))
print()
print("first integer:",int1)
print("second integer:",int2)
print("third integer:",int3)
print("first float:",fl1)
print("second float:",fl2)
print("third float:",fl3)
print("first string:",string1)
print("second string:",string2)
print("first complex:",cmpl6)

"""# Programs"""

#Program 1
initial=int(input("enter initial sugar candy wt:"))
final=(0.75)*initial
print("amount of candy kumar got",final)
remain=initial-final
print("amount of candyb sam got",remain)

#Program 2
n=float(input("enter a number"))
prod=3*n
add=56.19+prod
sub=add-10
result=sub
print("result:",result)

n1=int(input("enter a positive number:"))
n2=float(input("enter a negative float num:"))
mul=n1*n2
print("product:",mul)

"""# Operators


   ### 1.Arithmetic operators

*   addition  +
-subtraction  -
-multiplication  *
-dividion  (float)  /
-floor division  (int)  //
*   modulus  %

   ### 2.Relational/Comparision operators(compares two or more values)

* '>'
-<
-==
-<=
*   '>='
-!=

   ### 3.Logical operators

*   and
*   or
*   not

   ### 4.Assignment opeartors


*   =
*   +=
*   -=
*   *=
*   /=
"""

#arithmetic
print(11+11)
print(22-21)
print(12*2)
print(10/2)
print(10//2)
print(10%5)

#relational
print(10<22)
print(10>22)
print(1==2)
print(2>=3)
print(2>=2)
print(1!=2)

#logical
print(22>11 and 33<44)
print(22>11 or 33>44) 
print(not(1==2))
print(not(1==1))

"""# Multiple inputs in single line"""

n1,n2=input("enter two integers:").split(",")
print(n1)
print(n2)
print(n1+n2)

n1,n2=input("enter two integers:").split(".")
print(n1)
print(n2)
print(n1+n2)

n1,n2=input("enter two integers:").split(" ")
print(n1)
print(n2)
print(type(n1))
print(n1+n2)

n1,n2=input("enter two integers:").split(".")
print(n1)
print(n2)
print(int(n1)+int(n2))

"""# Programs

*   Swapping of numbers using temp
*   Swapping numbers without using temp
*   Area of rectangle
*   Perimeter of rectangle

"""



#swappingwithtemp
n1=int(input("Enter a number:"))
n2=int(input("Enter a number:"))
print("before swapping")
print("n1:",n1)
print("n2:",n2)
temp=n1
n1=n2
n2=temp
print("After swapping")
print("n1:",n1)
print("n2:",n2)



#swappingwithouttemp
n1=int(input("Enter a number:"))
n2=int(input("Enter a number:"))
print("before swapping")
print("n1:",n1)
print("n2:",n2)
total=n1+n2
n1=total-n1
n2=total-n2
print("After swapping")
print("n1:",n1)
print("n2:",n2)

#area
l=int(input("length:"))
b=int(input("breadth:"))
area=l*b
print("area of the rectangle:",area)

#perimeter
l=int(input("length:"))
b=int(input("breadth:"))
perimeter=2*(l+b)
print("perimeter of the rectangle:",perimeter)