# -*- coding: utf-8 -*-
"""DAY2(content&programs).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/180omMxJF1hItTro9JTYAD3OeGrloY1_K

# Bitwise operators

*   0's and 1's
*   some operations if u do like dz it wil be faster like compressing the  data
*   sending data in network to network 0 => false;1 => true 
*   bitwise AND - &
*   bitwise OR - |
*   NOT - ~
*   XOR - ^
*   LEFT SHIFT - <<
*   RIGHT SHIFT - >>
"""

#bitwise AND operator
print(10&4)
print(11&11)
n1=int(input())
n2=int(input())
n3=n1&n2
print(bin(n3))

#bitwise OR operator
print(10|4)
n1=int(input())
n2=int(input())
n3=n1|n2
print(bin(n3))

#bitwise NOT operator
print(~10)
print(~4)

#bitwise XOR operator
print(10^4)
n1=int(input())
n2=int(input())
n3=n1^n2
print(bin(n3))
print(9^8)

#left shift
print(10<<2)
print(bin(10<<2))

"""**get two numbers as input both less than or equal to 15 and perform and,or,xor** """

num1,num2=int(input("enter num1:")),int(input("enter num2:"))
print(bin(num1))
print(bin(num2))
print("bitwise and operation of:",num1&num2)
print("bitwise or opeartion:",num1|num2)
print("bitwise xor operstion:",num1^num2)

#Multiple inputs in one line
n=int(input("size:"))
a=list(map(int,input("numbers:").strip().split()))
print(a)

#Multiple inputs in one line
n=int(input("size:"))
a=list(map(int,input("numbers:").strip().split()))[:n]
print(a)

"""**Find the product of 10 integer numbers**"""

def product(numbers):
  result=1
  for i in numbers:
    result=result*i
  return result
numbers=list(map(int,input("Numbers:").split()))
print("result:",product(numbers))

print("It's","a","good","day",end="  ")
print("all","is","good",sep="**",end="   ")
print("It's","a","good","day")
print("all","is","good",sep=":",end="")
print("joy")

""" **using print statement print:**
*   **upside down filled triangle**
*   **hallow heart**
*   **frog**







"""

#Triangle
print("*","*","*","*","*",sep=" ")
print(" ","*","*","*"," ",sep=" ")
print(" "," ","*"," "," ",sep=" ")

#Hallow heart
print("*","*"," ","*","*",sep=" ")
print("*"," ","*"," ","*",sep=" ")
print(" ","*"," ","*"," ",sep=" ")
print(" "," ","*"," "," ",sep=" ")

#Frog

"""# Control/Conditonal statements
*   If
*   If else
*   Else if
*   Else if ladder
*   Nested if

Program using below conditions:
*   Temp>45::Hottest
*   Temp 40-45::Hot
*   Temp 25-40::Moderate
*   Temp 10-25::Cold
*   Temp below 10::Freezing
"""

Temp=int(input("Enter temperature:"))
if(Temp>45):
  print("Hottest")
elif(Temp>40 and Temp<=45):
  print("Hot")
elif(Temp>25 and Temp<=40):
  print("Moderate")
elif(Temp>10 and Temp<=25):
  print("Cold")
else:
  print("Freezing")

"""# Programs
*   **Get a number as input and find out whether it is 500 or not**
*   **Check the number is "even-positive" or "odd positive" or "even negative"or "odd negative"**
*   **Get 2 numbers as input and find out the biggest**
*   **Get 3 numbers as input and print the greatest number among those numbers**
*   **check given number is float or integer**
*   **Check the given number is divisible by 11 or not**
*   **Check the given number is divisible by both 2 and 5**
"""

#program 1
num=int(input("enter a number"))
if num==500:
  print("number is 500")
else:
  print("number is not 500")

#program 2
num=int(input("enter a number"))
if num%2==0:
  if num>=0:
    print("number is even-positive")
  if num<0:
    print("number is even-negative")
else:
  if num>=0:
    print("number is odd-positive")
  else:
    print("number is odd-negative")

#Program 3
num1,num2=int(input("enter num1:")),int(input("enter num2:"))
if num1>num2:
  print("num1 is the biggest number")
else:
  print("num2 is the biggest number")

#Program 5
num=input("enter a number")
if("." in num):
  print("the number is float")
else:
  print("the number is integer")

num=77
print(isinstance(num,int))
print(isinstance(num,float))

num=77.98
if(num%1==0):
  print("the number is integer")
else:
  print("The number is float")

n=10.3
res=n-int(n)
if(res!=0):
  print("Float")
else:
  print("integer")

#Program 4
num1,num2,num3=list(map(int,input("enter the numbers:").split()))
if (num1>num2 and num1>num3):
  print("num1 is the biggest number")
elif(num2>num1 and num2>num3):
  print("num2 is the biggest number")
else:
  print("num3 is the biggest number")

#Program 6
num=int(input("Enter a number:"))
if(num%11==0):
  print("The number is divisible by 11")
else:
  print("The number is not divisible by 11")

#Program 7
num=int(input("Enter a number:"))
if(num%2==0 and num%5==0):
  print("The number is divisible by both 2 and 5")
else:
  print("The number is not divisble by 2 and 5")

num=int(input())
rem=num%10
if rem==0:
  print("divisible by 2 and 5")
else:
  print("not divisible by 2 and 5")

"""# While loop"""

i=1
while i<=10:
  print(i)
  i=i+1

#even numbers 2 to 20
n=2
while n<=20:
  if n%2==0:
    print(n)
    n+=2

#Odd numbers from 1 to 30
n=1
while n<=30:
  if n%2!=0:
    print(n)
  n+=1

"""# For loop"""

for i in range(1,11):
  print(i)

for i in range(1,11,2):
  print(i)

import random
n=random.randrange(1,50)
guess=int(input("Enter a number:"))
while n!=guess:
  if guess<n:
    print("Too low")
    guess=int(input("Enter the number again"))
  elif guess>n:
    print("Too high")
    guess=int(input("Enter the number again"))
  else:
    break
print("Your guess is right")